{{- if and ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" ) ( .Values.prometheusrule.enabled ) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "zookeeper.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    monitoring: shared
    {{- include "zookeeper.labels.standard" . | nindent 4 }}
  {{- if .Values.prometheusrule.annotations }}
  annotations:
    {{- toYaml .Values.prometheusrule.annotations | nindent 4 }}
  {{- end }}
spec:
  groups:
    - name: {{ include "zookeeper.fullname" . }}
      rules:
        - alert: ZookeeperDown
          expr: up{job="zookeeper",pod=~".*zookeeper-[0-9]+"} == 0
          for: 3m
          labels:
            severity: warning
          annotations:
            summary: "Zookeeper instance is down"
            message: "Zookeeper is down on {{`{{ $labels.pod }}`}}. Could not scrape jmx-exporter for 3 minutes"
        - alert: ZookeeperSlow
          expr: max_over_time(zookeeper_maxrequestlatency[1m]) > 10000
          for: 3m
          labels:
            severity: warning
          annotations:
            summary: "Zookeeper high latency"
            message: "Zookeeper latency is {{`{{ $value }}`}}ms (aggregated over 1m) on {{`{{ $labels.pod }}`}}."
        - alert: ZookeeperEnsembleBroken
          expr: sum(up{job="zookeeper",pod=~".*zookeeper-[0-9]+"}) < 2
          for: 1m
          labels:
            severity: major
          annotations:
            summary: "Zookeeper ensemble is broken"
            message: "Zookeeper ensemble is broken, it has {{`{{ $value }}`}} nodes in it."
        - alert: ZookeeperLeaderNotAvailable
          expr: count(zookeeper_inmemorydatatree_nodecount{membertype="Leader"}) == 0
          for: 1m
          labels:
            severity: major
          annotations:
            summary: "Zookeeper leader is not available"
            message: "Zookeeper leader is not available, it has {{`{{ $value }}`}} leaders in it."
        - alert: ZookeeperMultipleLeaders
          expr: count(zookeeper_inmemorydatatree_nodecount{membertype="Leader"}) > 1
          for: 1m
          labels:
            severity: major
          annotations:
            summary: "Zookeeper has multiple leaders"
            message: "Zookeeper has multiple leaders, it has {{`{{ $value }}`}} leaders in it."
        - alert: ZookeeperAvgRequestLatency
          expr: zookeeper_avgrequestlatency > 10
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "Zookeeper average request latency"
            message: "The average request latency is {{`{{ $value }}`}} on {{`{{ $labels.pod }}`}}"
        - alert: ZookeeperOutstandingRequests
          expr: zookeeper_outstandingrequests > 10
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "Zookeeper outstanding requests"
            message: "There are {{`{{ $value }}`}} outstanding requests on {{`{{ $labels.pod }}`}}"
        - alert: ZookeeperContainerRestartedInTheLast5Minutes
          expr: count(count_over_time(container_last_seen{container_name="zookeeper"}[5m])) > 2 * count(container_last_seen{container_name="zookeeper",pod_name=~".*zookeeper-[0-9]+"})
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "One or more Zookeeper containers were restarted too often"
            message: "One or more Zookeeper containers were restarted too often within the last 5 minutes. This alert can be ignored when the Zookeeper cluster is scaling up"
        - alert: ZookeeperContainersDown
          expr: absent(container_last_seen{container_name="zookeeper",pod_name=~".*zookeeper-[0-9]+"})
          for: 5m
          labels:
            severity: major
          annotations:
            summary: "All zookeeper containers in the Zookeeper pods down or in CrashLookBackOff status"
            message: "All zookeeper containers in the Zookeeper pods have been down or in CrashLookBackOff status for 3 minutes"
{{- end }}
